task:
   name: MultiLabelSegmentation
   params:
      duration: 2.0
      batch_size: 32
      num_workers: 47
      classes: ['kchi', 'och', 'mal', 'fem', 'ovh']
      warm_up: 0.0
data_augmentation:
   name: Pipeline
   params:
      - name: AddNoise
        params:
           snr_min: 0
           snr_max: 20
           collection: MUSAN.Collection.BackgroundNoise
           target_rate: 16000
      - name: SpecAugment
        params:
           time_warping: 0.2
           freq_mask: 0.1
           time_mask: 0.1
           target_rate: 16000
feature_extraction:
   name: RawAudio
   params:
      sample_rate: 16000
architecture:
   name: voice_type_classifier.VoiceTypeClassifier
   params:
      hidden_size: 256
      num_transformer_layers: 4
      wav2vec_model: WAVLM_BASE
scheduler:
   name: voice_type_classifier.CosineAnnealingWithWarmup
   params:
      learning_rate: 1e-4
      warmup_epochs: 5
      max_epochs: 1 #TODO: set to 200
      warmup_start_lr: 1e-6
      min_lr: 1e-6
loss:
   name: BCEWithLogitsLoss
   params:
      weight: [1.0, 2.0, 1.0, 1.0, 1.0]